### ISSUE TITLE
Correct topic for Github YouTube-dl download blocking issues

### ISSUE THREAD

**Issue by GrimSq** [YelloNolo/YouTube-UnBlock#10]
Hi. I'm new here and I strongly suspect I have posted this in the wrong topic. If so, I hope you will be kind enough to direct me to the proper one. I have used YouTube-DL intensively at times in the past, but I tend to use it a lot, then not touch it for months, or longer. I now wanted to get the latest version for Windows, so I first did an internet search, and discovered the controversy over Github taking it down at one point. It appeared from those searches that Github had ultimately relented, and that YouTube-dl was freely available on Github once more. So I tried to download the windows exe file, from this page:
https://github.com/ytdl-org/youtube-dl

file link:
https://yt-dl.org/latest/youtube-dl.exe

and was shown this error message:
**_Access denied
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.
Zugriff gesperrt
Aufgrund eines [Urteils](https://openjur.de/u/2466945.html) des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt._**

- Did I misunderstand the outcome of the protests against Github for blocking YouTube-dl?
- Did GitHub relent and later reinstate the block? 
- Or is the lock on that exe file possibly a legacy of the rescinded block that was never corrected?
- Any suggestions for me to get the latest version installed on my Windows box?

Thank you in advance for any assistance you can provide.

Grima S

**Comment by YelloNolo** [comment]
There seems to be a reddit post on this topic: https://www.reddit.com/r/youtubedl/s/84gtjjwvYX

And others saying yt-dlp is a better alternative anyways. Here is a source: https://www.reddit.com/r/archlinux/s/LQKlFzc6OQ
