### ISSUE TITLE
when using yout-ube video plays multiple times in the same page

### ISSUE THREAD

**Issue by guigadj** [YelloNolo/YouTube-UnBlock#5]
when i use yout-ube option, the audio starts multiple times and play at the same time out of sync

**Comment by YelloNolo** [comment]
I'm looking into this. Does this happen to only playlists, or all videos? 

Also, I recently fixed a different bug, It might have fixed this issue as well.

**Comment by YelloNolo** [comment]
I believe I finally fixed the issue. If it persists, let me know and reopen this issue. 
Keep in mind, playlist are currently broken. This is under investigation.
